import type { TestResult } from "../../store/ReportContext";
import { groupResultsByTest } from "./groupResults";
import { formatReferenceRange } from "./referenceRange";
import { accession, formatReportDate } from "./reportMeta";

/**
 * Single source of truth for what a house-format report *says* and in what
 * order. Both renderers — the on-screen/print DOM (`PrintableReport`) and the
 * downloadable PDF (`reportPdf`) — consume this model, so wording, section
 * order, grouping and labels can only be defined once. Only visual styling
 * lives in each renderer.
 */

export interface ReportContent {
  specimenType: string;
  clinicalHistory: string;
  findings: string;
  diagnosis: string;
  testResults: TestResult[];
}

export interface ReportModelInput {
  patientName: string;
  patientCode: string;
  reportId?: string;
  version: number;
  isFinalized: boolean;
  finalizedAt?: string;
  panelName?: string;
  department?: string;
  reportDate?: string;
  content: ReportContent;
}

export interface ReportResultRow {
  key: string;
  name: string;
  value: string;
  numeric: boolean;
  unit: string;
  reference: string;
}

export interface ReportResultGroup {
  key: string;
  testName: string;
  rows: ReportResultRow[];
}

export interface ReportNarrative {
  heading: string;
  body: string;
  emphasis: boolean;
}

export interface ReportSignoff {
  role: string;
  note: string;
}

export interface ReportModel {
  brand: { name: string; tagline: string; strapline: string };
  documentTitle: string;
  reportNo: string;
  version: number;
  statusLabel: string;
  isFinalized: boolean;
  draftNotice: string | null;
  band: { label: string; value: string }[];
  resultsHeading: string;
  resultGroups: ReportResultGroup[];
  showGroupHeadings: boolean;
  narratives: ReportNarrative[];
  signoff: ReportSignoff[];
  authorisationNote: string;
  endOfReport: string;
  footer: { reference: string; disclaimer: string };
  /** Suggested file name (no extension) for the downloadable PDF. */
  fileBaseName: string;
}

const BRAND = {
  name: "PathForge",
  tagline: "Clinical & Anatomic Pathology",
  strapline:
    "Diagnostic laboratory report · Generated by the PathForge workspace",
};

const DRAFT_NOTICE =
  "Preliminary draft — not for clinical use. Findings are subject to review and may change before the report is finalized.";

const AUTH_NOTE_FINAL =
  "This report has been electronically verified and released. A handwritten signature is not required.";
const AUTH_NOTE_DRAFT =
  "This preliminary report has not been verified and must not be used for clinical decisions.";

const DISCLAIMER =
  "Computer-generated report for the named patient and referring clinician only.";

const NOT_PROVIDED = "Not provided";

function isNumeric(value: string): boolean {
  return value.trim() !== "" && !Number.isNaN(Number(value));
}

export function buildReportModel(input: ReportModelInput): ReportModel {
  const reportNo = accession(input.reportId, input.version);
  const patientSlug =
    input.patientName.trim().replace(/\s+/g, "_").replace(/[^\w-]/g, "") ||
    "Report";

  const groups = groupResultsByTest(input.content.testResults);
  const resultGroups: ReportResultGroup[] = groups.map((group) => ({
    key: group.key,
    testName: group.testName,
    rows: group.results.map((result) => ({
      key: `${result.testId}::${result.parameterId}`,
      name: result.parameterName,
      value: result.value || NOT_PROVIDED,
      numeric: isNumeric(result.value),
      unit: result.unit || "—",
      reference: formatReferenceRange(result.referenceRange),
    })),
  }));

  return {
    brand: BRAND,
    documentTitle: "Pathology Report",
    reportNo,
    version: input.version,
    statusLabel: input.isFinalized ? "Final" : "Draft",
    isFinalized: input.isFinalized,
    draftNotice: input.isFinalized ? null : DRAFT_NOTICE,
    band: [
      { label: "Patient Name", value: input.patientName },
      { label: "Patient ID", value: input.patientCode },
      { label: "Specimen", value: input.content.specimenType || "Not specified" },
      { label: "Panel", value: input.panelName || "—" },
      { label: "Department", value: input.department || "—" },
      { label: "Registered", value: formatReportDate(input.reportDate) },
    ],
    resultsHeading: "Laboratory Results",
    resultGroups,
    showGroupHeadings: resultGroups.length > 1,
    narratives: [
      {
        heading: "Clinical History",
        body: input.content.clinicalHistory || NOT_PROVIDED,
        emphasis: false,
      },
      {
        heading: "Microscopic Findings",
        body: input.content.findings || NOT_PROVIDED,
        emphasis: false,
      },
      {
        heading: "Diagnosis",
        body: input.content.diagnosis || NOT_PROVIDED,
        emphasis: true,
      },
    ],
    signoff: [
      {
        role: "Performed & reported by",
        note: "PathForge Clinical Pathology Workspace",
      },
      {
        role: "Verified & authorised by",
        note: input.isFinalized
          ? `Electronically verified ${formatReportDate(input.finalizedAt)}`
          : "Pending verification",
      },
    ],
    authorisationNote: input.isFinalized ? AUTH_NOTE_FINAL : AUTH_NOTE_DRAFT,
    endOfReport: "— End of Report —",
    footer: { reference: `${BRAND.name} · ${reportNo}`, disclaimer: DISCLAIMER },
    fileBaseName: `PathForge_${patientSlug}_${reportNo}`,
  };
}
